version: '2'
services:
  fluentd:
    build: ./docker/fluentd
    volumes:
      - ./docker/fluentd/conf:/fluentd/etc
    networks:
      default: {}
      sf_monitoring:
        aliases: [fluentd]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

networks:
  sf_monitoring:
    external: true
